//! src/ntexapi_h.rs

// This module contains custom type defs from ntexapi.





use std::ffi::{c_void};
use std::os::raw::{c_ulong, c_ushort};


#[repr(u32)]
pub enum SystemInformationClass
{
    SystemBasicInformation,
    SystemProcessorInformation,
    SystemPerformanceInformation,
    SystemTimeOfDayInformation,
    SystemPathInformation,
    SystemProcessInformation,
    SystemCallCountInformation,
    SystemDeviceInformation,
    SystemProcessorPerformanceInformation,
    SystemFlagsInformation,
    SystemCallTimeInformation,
    SystemModuleInformation,
    SystemLocksInformation,
    SystemStackTraceInformation,
    SystemPagedPoolInformation,
    SystemNonPagedPoolInformation,
    SystemHandleInformation,
    SystemObjectInformation,
    SystemPageFileInformation,
    SystemVdmInstemulInformation,
    SystemVdmBopInformation,
    SystemFileCacheInformation,
    SystemPoolTagInformation,
    SystemInterruptInformation,
    SystemDpcBehaviorInformation,
    SystemFullMemoryInformation,
    SystemLoadGdiDriverInformation,
    SystemUnloadGdiDriverInformation,
    SystemTimeAdjustmentInformation,
    SystemSummaryMemoryInformation,
    SystemMirrorMemoryInformation,
    SystemPerformanceTraceInformation,
    SystemObsolete0,
    SystemExceptionInformation,
    SystemCrashDumpStateInformation,
    SystemKernelDebuggerInformation,
    SystemContextSwitchInformation,
    SystemRegistryQuotaInformation,
    SystemExtendServiceTableInformation,
    SystemPrioritySeperation,
    SystemVerifierAddDriverInformation,
    SystemVerifierRemoveDriverInformation,
    SystemProcessorIdleInformation,
    SystemLegacyDriverInformation,
    SystemCurrentTimeZoneInformation,
    SystemLookasideInformation,
    SystemTimeSlipNotification,
    SystemSessionCreate,
    SystemSessionDetach,
    SystemSessionInformation,
    SystemRangeStartInformation,
    SystemVerifierInformation,
    SystemVerifierThunkExtend,
    SystemSessionProcessInformation,
    SystemLoadGdiDriverInSystemSpace,
    SystemNumaProcessorMap,
    SystemPrefetcherInformation,
    SystemExtendedProcessInformation,
    SystemRecommendedSharedDataAlignment,
    SystemComPlusPackage,
    SystemNumaAvailableMemory,
    SystemProcessorPowerInformation,
    SystemEmulationBasicInformation,
    SystemEmulationProcessorInformation,
    SystemExtendedHandleInformation,
    SystemLostDelayedWriteInformation,
    SystemBigPoolInformation,
    SystemSessionPoolTagInformation,
    SystemSessionMappedViewInformation,
    SystemHotpatchInformation,
    SystemObjectSecurityMode,
    SystemWatchdogTimerHandler,
    SystemWatchdogTimerInformation,
    SystemLogicalProcessorInformation,
    SystemWow64SharedInformationObsolete,
    SystemRegisterFirmwareTableInformationHandler,
    SystemFirmwareTableInformation,
    SystemModuleInformationEx,
    SystemVerifierTriageInformation,
    SystemSuperfetchInformation,
    SystemMemoryListInformation,
    SystemFileCacheInformationEx,
    SystemThreadPriorityClientIdInformation,
    SystemProcessorIdleCycleTimeInformation,
    SystemVerifierCancellationInformation,
    SystemProcessorPowerInformationEx,
    SystemRefTraceInformation,
    SystemSpecialPoolInformation,
    SystemProcessIdInformation,
    SystemErrorPortInformation,
    SystemBootEnvironmentInformation,
    SystemHypervisorInformation,
    SystemVerifierInformationEx,
    SystemTimeZoneInformation,
    SystemImageFileExecutionOptionsInformation,
    SystemCoverageInformation,
    SystemPrefetchPatchInformation,
    SystemVerifierFaultsInformation,
    SystemSystemPartitionInformation,
    SystemSystemDiskInformation,
    SystemProcessorPerformanceDistribution,
    SystemNumaProximityNodeInformation,
    SystemDynamicTimeZoneInformation,
    SystemCodeIntegrityInformation,
    SystemProcessorMicrocodeUpdateInformation,
    SystemProcessorBrandString,
    SystemVirtualAddressInformation,
    SystemLogicalProcessorAndGroupInformation,
    SystemProcessorCycleTimeInformation,
    SystemStoreInformation,
    SystemRegistryAppendString,
    SystemAitSamplingValue,
    SystemVhdBootInformation,
    SystemCpuQuotaInformation,
    SystemNativeBasicInformation,
    SystemErrorPortTimeouts,
    SystemLowPriorityIoInformation,
    SystemTpmBootEntropyInformation,
    SystemVerifierCountersInformation,
    SystemPagedPoolInformationEx,
    SystemSystemPtesInformationEx,
    SystemNodeDistanceInformation,
    SystemAcpiAuditInformation,
    SystemBasicPerformanceInformation,
    SystemQueryPerformanceCounterInformation,
    SystemSessionBigPoolInformation,
    SystemBootGraphicsInformation,
    SystemScrubPhysicalMemoryInformation,
    SystemBadPageInformation,
    SystemProcessorProfileControlArea,
    SystemCombinePhysicalMemoryInformation,
    SystemEntropyInterruptTimingInformation,
    SystemConsoleInformation,
    SystemPlatformBinaryInformation,
    SystemPolicyInformation,
    SystemHypervisorProcessorCountInformation,
    SystemDeviceDataInformation,
    SystemDeviceDataEnumerationInformation,
    SystemMemoryTopologyInformation,
    SystemMemoryChannelInformation,
    SystemBootLogoInformation,
    SystemProcessorPerformanceInformationEx,
    SystemCriticalProcessErrorLogInformation,
    SystemSecureBootPolicyInformation,
    SystemPageFileInformationEx,
    SystemSecureBootInformation,
    SystemEntropyInterruptTimingRawInformation,
    SystemPortableWorkspaceEfiLauncherInformation,
    SystemFullProcessInformation,
    SystemKernelDebuggerInformationEx,
    SystemBootMetadataInformation,
    SystemSoftRebootInformation,
    SystemElamCertificateInformation,
    SystemOfflineDumpConfigInformation,
    SystemProcessorFeaturesInformation,
    SystemRegistryReconciliationInformation,
    SystemEdidInformation,
    SystemManufacturingInformation,
    SystemEnergyEstimationConfigInformation,
    SystemHypervisorDetailInformation,
    SystemProcessorCycleStatsInformation,
    SystemVmGenerationCountInformation,
    SystemTrustedPlatformModuleInformation,
    SystemKernelDebuggerFlags,
    SystemCodeIntegrityPolicyInformation,
    SystemIsolatedUserModeInformation,
    SystemHardwareSecurityTestInterfaceResultsInformation,
    SystemSingleModuleInformation,
    SystemAllowedCpuSetsInformation,
    SystemVsmProtectionInformation,
    SystemInterruptCpuSetsInformation,
    SystemSecureBootPolicyFullInformation,
    SystemCodeIntegrityPolicyFullInformation,
    SystemAffinitizedInterruptProcessorInformation,
    SystemRootSiloInformation,
    SystemCpuSetInformation,
    SystemCpuSetTagInformation,
    SystemWin32WerStartCallout,
    SystemSecureKernelProfileInformation,
    SystemCodeIntegrityPlatformManifestInformation,
    SystemInterruptSteeringInformation,
    SystemSupportedProcessorArchitectures,
    SystemMemoryUsageInformation,
    SystemCodeIntegrityCertificateInformation,
    SystemPhysicalMemoryInformation,
    SystemControlFlowTransition,
    SystemKernelDebuggingAllowed,
    SystemActivityModerationExeState,
    SystemActivityModerationUserSettings,
    SystemCodeIntegrityPoliciesFullInformation,
    SystemCodeIntegrityUnlockInformation,
    SystemIntegrityQuotaInformation,
    SystemFlushInformation,
    SystemProcessorIdleMaskInformation,
    SystemSecureDumpEncryptionInformation,
    SystemWriteConstraintInformation,
    SystemKernelVaShadowInformation,
    SystemHypervisorSharedPageInformation,
    SystemFirmwareBootPerformanceInformation,
    SystemCodeIntegrityVerificationInformation,
    SystemFirmwarePartitionInformation,
    SystemSpeculationControlInformation,
    SystemDmaGuardPolicyInformation,
    SystemEnclaveLaunchControlInformation,
    SystemWorkloadAllowedCpuSetsInformation,
    SystemCodeIntegrityUnlockModeInformation,
    SystemLeapSecondInformation,
    SystemFlags2Information,
    SystemSecurityModelInformation,
    SystemCodeIntegritySyntheticCacheInformation,
    SystemFeatureConfigurationInformation,
    SystemFeatureConfigurationSectionInformation,
    SystemFeatureUsageSubscriptionInformation,
    SystemSecureSpeculationControlInformation,
    SystemSpacesBootInformation,
    SystemFwRamdiskInformation,
    SystemWheaIpmiHardwareInformation,
    SystemDifSetRuleClassInformation,
    SystemDifClearRuleClassInformation,
    SystemDifApplyPluginVerificationOnDriver,
    SystemDifRemovePluginVerificationOnDriver,
    SystemShadowStackInformation,
    SystemBuildVersionInformation,
    SystemPoolLimitInformation,
    SystemCodeIntegrityAddDynamicStore,
    SystemCodeIntegrityClearDynamicStores,
    SystemDifPoolTrackingInformation,
    SystemPoolZeroingInformation,
    SystemDpcWatchdogInformation,
    SystemDpcWatchdogInformation2,
    SystemSupportedProcessorArchitectures2,
    SystemSingleProcessorRelationshipInformation,
    SystemXfgCheckFailureInformation,
    SystemIommuStateInformation,
    SystemHypervisorMinrootInformation,
    SystemHypervisorBootPagesInformation,
    SystemPointerAuthInformation,
    SystemSecureKernelDebuggerInformation,
    SystemOriginalImageFeatureInformation,
    SystemMemoryNumaInformation,
    SystemMemoryNumaPerformanceInformation,
    SystemCodeIntegritySignedPoliciesFullInformation,
    SystemSecureSecretsInformation,
    SystemTrustedAppsRuntimeInformation,
    SystemBadPageInformationEx,
    SystemResourceDeadlockTimeout,
    SystemBreakOnContextUnwindFailureInformation,
    SystemOslRamdiskInformation,
    MaxSystemInfoClass,
}



#[repr(C)]
pub struct SYSTEM_HANDLE_TABLE_ENTRY_INFO
{
    pub(crate) process_id: u16,
    creator_back_trace_index: u16,
    pub(crate) object_type_index: u8,
    handle_attributes: u8,
    handle_value: u16,
    object: *mut c_void,
    granted_access: u32,
}


#[repr(C)]
pub struct SYSTEM_HANDLE_TABLE_ENTRY_INFO_EX
{
    pub(crate) Object: *mut c_void,
    pub(crate) UniqueProcessId: usize,
    HandleValue: usize,
    GrantedAccess: c_ulong,
    CreatorBackTraceIndex: c_ushort,
    ObjectTypeIndex: c_ushort,
    HandleAttributes: c_ulong,
    Reserved: c_ulong,
}


#[repr(C)]
pub(crate) struct SYSTEM_HANDLE_INFORMATION
{
    pub(crate) ProcessId: u32,
    ObjectTypeNumber: u8,
    Flags: u8,
    Handle: u16,
    pub(crate) Object: *mut c_void,
    GrantedAccess: u32,
    pub(crate) handle_count: usize,
    pub(crate) handles: [SYSTEM_HANDLE_TABLE_ENTRY_INFO; 1],
}


/*
#[repr(C)]
pub(crate) struct SYSTEM_HANDLE_INFORMATION {
    pub(crate) handle_count: usize,
    pub(crate) handles: [SYSTEM_HANDLE_TABLE_ENTRY_INFO; 1],
}
*/

#[repr(C)]
pub struct SYSTEM_HANDLE_INFORMATION_EX
{
    pub(crate) NumberOfHandles: u32,
    Reserved: u32,
    pub(crate) Handles: [SYSTEM_HANDLE_INFORMATION; 1], // This is actually a flexible array member in C
}
